spring:
  datasource:
    url: jdbc:mysql://115.29.199.159:3306/ballcat?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 'xxc5201314'
  redis:
    host: 115.29.199.159
    password: 'xxc520'
    port: 6379

ballcat:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key: your key here
    access-secret: your secret here
    bucket: your-bucket-here
